name: Build and Archive Gradle project

on:
  push:
    branches:
    - "main"
    - "master"

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-java@v5
        with:
          distribution: temurin
          java-version: 25
      - name: Checkout project sources
        uses: actions/checkout@v5
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v6
      - name: Make gradlew executable
        run: chmod +x ./gradlew
      - name: Run build with Gradle Wrapper
        run: ./gradlew build
      - uses: actions/upload-artifact@v7
        with:
          name: build-outputs
          path: build/libs/*.jar
